# Generated by Django 4.0.3 on 2022-03-25 04:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolistitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 11, 25, 44, 18804)),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
